version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=forumgs
      - POSTGRES_USER=gabs
      - POSTGRES_PASSWORD=dataBase01@
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=dbGraphs01@
    ports:
      - 5050:80
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=forumgs
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mysqlBase01@
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=mysqlBase01@
    ports:
      - 8080:80
